### ISSUE TITLE
Add Funkwhale

### ISSUE THREAD

**Issue by testman42** [redecentralize/alternative-internet#272]
Funkwhale is free and open source platform for playing and sharing music.
https://funkwhale.audio/
https://dev.funkwhale.audio/funkwhale

**Comment by strypey** [comment]
Is this list still being maintained? I don't know if it's suitable to add fediverse.party, but it's also a guide to a range of federated social media/ network software, which are all decentralization projects. Any or all of these could be added to this list. We also have a wiki where we list other decentralization projects that are outside our scope, such as blockchain social media/ network projects, or those based on XMPP or Matrix instead of the fediverse protocols (Diaspora, OStatus, ActivityPub, Zot).

**Comment by testman42** [comment]
> Is this list still being maintained?

[yes](https://dev.funkwhale.audio/groups/funkwhale/-/activity)

**Comment by rossjones** [comment]
Just adding it now
